extend = "common.toml"

[env]
COMMON_TOML = "https://github.com/vita-rust/common/raw/master/common.toml"

[config]
load_script = ["if [ ! -f common.toml ]; then curl -SsL ${COMMON_TOML} > common.toml; fi"]

[tasks.default]
alias = "build"


### TESTING ####################################################################

[tasks.build-native]
command = "cargo"
args = ["build"]

[tasks.test-native]
command = "cargo"
args = ["test"]
